name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        scala: [2.11.12, 2.12.10, 2.13.6]
        module: [db, js, async, codegen, bigdata]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java and Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: 1.8.0

    - run: export TRAVIS_SCALA_VERSION=${{ matrix.scala }}
    - run: ./build/build.sh ${{ matrix.module }}
    
  release:
    runs-on: ubuntu-latest
    
    needs: build
    
    strategy:
      matrix:
        scala: [2.11.12, 2.12.10, 2.13.6]
        module: [db, js, async, codegen, bigdata]
        include:
        - scala: 2.11.12
          scala_short: 211
        - scala: 2.12.10
          scala_short: 212
        - scala: 2.13.6
          scala_short: 213

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java and Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: 1.8.0

    - run: export TRAVIS_SCALA_VERSION=${{ matrix.scala }}
    - run: export TRAVIS_BRANCH=$(git for-each-ref ${{ github.ref }} --format='%(refname:short)')
    - run: ./build/release.sh ${{ matrix.scala_short }} ${{ matrix.module }}
